# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 4205797f44becc670253102ac80bf1dc4ec3d64725071e9ea2844e420ce0d2d20f7d2408cef7ef6b85a81436bd24a4092ac3a7739b6aaa389e82834a66e291c8

test:
  secret_key_base: 34f418974cd4f258339c2eb5342e29711eb311080044a56f547adcf1f1f678640f038f7dfdeca935c4e95da5f1c6604033bfa081a66751faa106691ce086ac67

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
